# Generated by Django 5.1 on 2026-04-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory_context', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='memoryblock',
                    new_name='memory_cont_tier_fc176d_idx',
                    old_name='mem_ctx_tier_ref_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='memoryblock',
                    new_name='memory_cont_tier_49abef_idx',
                    old_name='mem_ctx_tier_ref_type_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='memoryblock',
                    new_name='memory_cont_tier_241ca1_idx',
                    old_name='mem_ctx_tier_active_prio_idx',
                ),
            ],
        ),
    ]
