# Generated by Django 5.1 on 2026-04-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_trail', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='auditlog',
                    new_name='audit_trail_user_id_16037d_idx',
                    old_name='audit_trail_user_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='auditlog',
                    new_name='audit_trail_categor_73ef46_idx',
                    old_name='audit_trail_cat_op_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='auditlog',
                    new_name='audit_trail_project_70b3b0_idx',
                    old_name='audit_trail_proj_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='auditlog',
                    new_name='audit_trail_status_d5fd32_idx',
                    old_name='audit_trail_status_idx',
                ),
            ],
        ),
    ]
