# Generated by Django 5.1 on 2026-04-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification_hub', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='notification',
                    new_name='notificatio_user_id_8cbe7d_idx',
                    old_name='notif_hub_user_read_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='notification',
                    new_name='notificatio_user_id_3680dd_idx',
                    old_name='notif_hub_user_idx',
                ),
            ],
        ),
    ]
