# Generated by Django 5.1 on 2026-04-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_factory', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='agenteventlog',
                    new_name='agent_facto_agent_t_702789_idx',
                    old_name='af_event_type_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='agenteventlog',
                    new_name='agent_facto_job_id_43c2f4_idx',
                    old_name='af_event_job_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='agentusagelog',
                    new_name='agent_facto_agent_t_bdc854_idx',
                    old_name='af_usage_type_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='jobqueue',
                    new_name='agent_facto_status_c2bf8d_idx',
                    old_name='af_job_status_prio_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='jobqueue',
                    new_name='agent_facto_agent_t_d784d3_idx',
                    old_name='af_job_type_status_idx',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='agenttemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
